# Funding platforms for MyVoice-TTS
# Support the development of accessible voice communication

ko_fi: myvoicetts

# GitHub Sponsors - Uncomment after approval (submitted 2026-02-15)
# github: WreckedMech117
